config/routes.rb
Rails.application.routes.draw do
root "billboards#index"

resources :billboards do
  resources :songs
end

# resources :artists do
#   resources :songs
# end



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs
end

app/models/billboard.rb
class Billboard < ApplicationRecord
  has_many :songs
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :billboard
  belongs_to :artist
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
  
  end

  def show
  
  end

  def edit
  
  end

  def create

  end

  def new
  
  end

  def update

  end

  def destroy

  end

  private
end

app/controllers/billboards_controller.rb
class BillboardsController < ApplicationController
  before_action :set_billboard, only: [:show, :edit, :update, :destroy]

  
  def index
    @billboards = Billboard.all
  end

  def show
  end

  def create
    @billboard = Billboard.new(billboard_params)
    if @billboard.save
      redirect_to billboards_path
    else
      render :new
    end
  end

  def edit
  end

  def new
    @billboard = Billboard.new
  end

  def update
    if @billboard.update(billboard_params)
      redirect_to billboards_path
    else
      render :new
    end
  end

  def destroy
    @billboard.destroy
    redirect_to billboards_path
  end

  private
  def set_billboard
    @billboards = Billboard.find(params[:id])
  end

  def billboard_params
    params.require(:billboard).permit(:title)
  end


end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def index
  
  end

  def show
  
  end

  def edit
  
  end

  def create

  end

  def new
  
  end

  def update

  end

  def destroy

  end

  private
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/billboards_helper.rb
module BillboardsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/edit.html.erb
<h1>Artists#edit</h1>
<p>Find me in app/views/artists/edit.html.erb</p>

app/views/artists/index.html.erb
<h1>Artists#index</h1>
<p>Find me in app/views/artists/index.html.erb</p>

app/views/artists/new.html.erb
<h1>Artists#new</h1>
<p>Find me in app/views/artists/new.html.erb</p>

app/views/artists/show.html.erb
<h1>Artists#show</h1>
<p>Find me in app/views/artists/show.html.erb</p>

app/views/billboards/_form.html.erb
<h1>  <%= @sub.id ? "Edit Sub" : "Create Sub" %> </h1>
<hr />
<%= form_for @sub do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <%= f.submit %>
<% end %>

app/views/billboards/edit.html.erb
<h1>Edit Sub</h1>
<hr />
<%= form_for @sub do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name, required: true, autofocus: true %>
  <%= f.submit %>
<% end %>

app/views/billboards/index.html.erb
<h1 class="ui header">Billboards</h1>
<%= link_to 'New Billboard', new_billboard_path %>
<div class="ui divider"></div>

<div class="ui grid">
  <% @billboards.each do |billboard| %>
    <div class="sixteen wide mobile eight wide tablet four wide computer column">
      <div class="ui card">
        <div class="image">
          <img src="https://robohash.org/<%= billboard.avatar %>?set=set4" />
        </div>
        <div class="content">
          <%= link_to "#{billboard.name}", billboard, class: "header" %>
        </div>
        <div class="extra content">
          <div class="ui two buttons">
            <div class="ui basic green button">
              <%= link_to 'Edit', edit_bilboard_path(billboard) %>
            </div>
            <div class="ui basic red button">
              <%= link_to 'Destroy', billboard, method: :delete, data: { confirm: 'Are you sure?' } %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/billboards/new.html.erb
<h1>Billboards#new</h1>
<p>Find me in app/views/billboards/new.html.erb</p>

app/views/billboards/show.html.erb
<h1><%= @sub.name %></h1>
<hr />
<p>What would you like to do?</p>
<%= link_to 'View Topics', sub_topics_path(@sub) %>
<br />#
<%= link_to 'Edit Sub', edit_sub_path(@sub) %>
<br />
<%= link_to 'Delete Sub', @sub, method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MusicApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/songs/edit.html.erb
<h1>Songs#edit</h1>
<p>Find me in app/views/songs/edit.html.erb</p>

app/views/songs/index.html.erb
<h1>Songs#index</h1>
<p>Find me in app/views/songs/index.html.erb</p>

app/views/songs/new.html.erb
<h1>Songs#new</h1>
<p>Find me in app/views/songs/new.html.erb</p>

app/views/songs/show.html.erb
<h1>Songs#show</h1>
<p>Find me in app/views/songs/show.html.erb</p>